#!/bin/bash

# Скрипт отправки данных на соседний сервер

PROG_NAME=$(basename $0)
destination=alexander@localhost
file_name="deliv_log_$(date +%F-%T)"

# Проверка наличия прав root, без них не получится писать в папку /var/log
if (( $(id -u) != 0)) ; then
    echo "$PROG_NAME: error, this script needs root privileges." >&2
    exit 1
fi

# Возможность задания сервера назначения в первом позиционном параметре
if [ "$1" ]; then
    destination=$1
fi

# Генерация файла для отправки
echo "$(date)" > "/var/log/${file_name}"

# Проверка создана ли папка для файлов на принимающем сервере
if ssh "$destination" '[ ! -d ~/deliv_log ]'; then
    # Создание папки, если её нет
    if ! ssh "$destination" 'mkdir ~/deliv_log'; then
        # Ошибка, если не получилось создать папку и выход
        echo "$PROG_NAME: error, unable to create directory." >&2
        exit 2
    fi
fi

# Копирование файла на сервер назначения
scp "/var/log/${file_name}" "$destination:~/deliv_log"

# Удаление старых файлов
ssh "$destination" 'find ~/deliv_log/ -type f -mtime +7 -delete'
