#!/bin/bash

# Скрипт отправки данных на соседний сервер

PROG_NAME=$(basename $0)
destination=localhost
file_name=deliv_log

if (( $(id -u) != 0)) ; then
    echo "$PROG_NAME: error, this script needs root privileges." >&2
    exit 1
fi

echo "$(date)" > "/var/log/${file_name}_$(date +%F-%T)"
